version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: employee_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: employee_db
      DB_USER: admin
      DB_PASSWORD: admin_password
      DB_HOST: db
      DB_PORT: 3306
      SECRET_KEY: mysecretkey
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  client:
    build: ./client
    container_name: client_app
    restart: on-failure
    depends_on:
      - web
    environment:
      API_URL: http://web:8000/api/employees/
    volumes:
      - ./client:/app
    networks:
      - default

volumes:
  mysql_data:
