FROM python:3.10

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy script and CSV
COPY send_records.py .
COPY employees.csv .

CMD ["python", "send_records.py"]
